# Form implementation generated from reading ui file 'Create.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(533, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/translation.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(50, 70, 461, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.progressLabel = QtWidgets.QLabel(Dialog)
        self.progressLabel.setGeometry(QtCore.QRect(50, 120, 421, 16))
        self.progressLabel.setObjectName("progressLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Minecraft Mods 辅助翻译器"))
        self.progressLabel.setText(_translate("Dialog", "加载中..."))
