# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/translation.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ImportJar = QtWidgets.QPushButton(self.centralwidget)
        self.ImportJar.setGeometry(QtCore.QRect(30, 20, 93, 28))
        self.ImportJar.setObjectName("ImportJar")
        self.Status = QtWidgets.QTextBrowser(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(30, 60, 181, 321))
        self.Status.setObjectName("Status")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 150, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 230, 41, 16))
        self.label_3.setObjectName("label_3")
        self.Tag = QtWidgets.QTextBrowser(self.centralwidget)
        self.Tag.setGeometry(QtCore.QRect(340, 70, 241, 51))
        self.Tag.setObjectName("Tag")
        self.Origin = QtWidgets.QTextBrowser(self.centralwidget)
        self.Origin.setGeometry(QtCore.QRect(340, 150, 241, 51))
        self.Origin.setObjectName("Origin")
        self.Translated = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Translated.setGeometry(QtCore.QRect(340, 230, 241, 51))
        self.Translated.setObjectName("Translated")
        self.Unchecked = QtWidgets.QLabel(self.centralwidget)
        self.Unchecked.setGeometry(QtCore.QRect(300, 330, 121, 16))
        self.Unchecked.setObjectName("Unchecked")
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setEnabled(False)
        self.Next.setGeometry(QtCore.QRect(490, 320, 93, 31))
        self.Next.setObjectName("Next")
        self.isRestart = QtWidgets.QCheckBox(self.centralwidget)
        self.isRestart.setGeometry(QtCore.QRect(140, 20, 91, 31))
        self.isRestart.setObjectName("isRestart")
        self.Finish = QtWidgets.QPushButton(self.centralwidget)
        self.Finish.setEnabled(False)
        self.Finish.setGeometry(QtCore.QRect(610, 30, 93, 28))
        self.Finish.setObjectName("Finish")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Minecraft Mods 辅助翻译器"))
        self.ImportJar.setText(_translate("MainWindow", "导入文件"))
        self.label.setText(_translate("MainWindow", "原文："))
        self.label_2.setText(_translate("MainWindow", "Tag："))
        self.label_3.setText(_translate("MainWindow", "译文："))
        self.Unchecked.setText(_translate("MainWindow", "还剩 0 个未校对"))
        self.Next.setText(_translate("MainWindow", "下一条"))
        self.isRestart.setText(_translate("MainWindow", "重新翻译"))
        self.Finish.setText(_translate("MainWindow", "完成"))
